// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbSf4O7TkTQj65C-pyeuGddxxWSP8o76s',
    appId: '1:751927667003:web:1713a32350a2ceec89af1e',
    messagingSenderId: '751927667003',
    projectId: 'chatsapp-97bc2',
    authDomain: 'chatsapp-97bc2.firebaseapp.com',
    databaseURL: 'https://chatsapp-97bc2-default-rtdb.firebaseio.com',
    storageBucket: 'chatsapp-97bc2.appspot.com',
    measurementId: 'G-H3E64F1TTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz1J1Oz9e93pdtd6de4ahjXnEDmX7oKRg',
    appId: '1:751927667003:android:ad8e33be34c0178089af1e',
    messagingSenderId: '751927667003',
    projectId: 'chatsapp-97bc2',
    databaseURL: 'https://chatsapp-97bc2-default-rtdb.firebaseio.com',
    storageBucket: 'chatsapp-97bc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4u7LYAgsHl4CSN89SSIP7pZ6NaxsYUUc',
    appId: '1:751927667003:ios:86e6c082fa3a7c7089af1e',
    messagingSenderId: '751927667003',
    projectId: 'chatsapp-97bc2',
    databaseURL: 'https://chatsapp-97bc2-default-rtdb.firebaseio.com',
    storageBucket: 'chatsapp-97bc2.appspot.com',
    iosBundleId: 'com.example.chatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4u7LYAgsHl4CSN89SSIP7pZ6NaxsYUUc',
    appId: '1:751927667003:ios:849d1938555380c489af1e',
    messagingSenderId: '751927667003',
    projectId: 'chatsapp-97bc2',
    databaseURL: 'https://chatsapp-97bc2-default-rtdb.firebaseio.com',
    storageBucket: 'chatsapp-97bc2.appspot.com',
    iosBundleId: 'com.example.chatsApp.RunnerTests',
  );
}
